export const sampleProjects = [
  {
    id: "demo-1",
    name: "Downtown Civic Center",
    location: "San Francisco, CA",
    status: "in-progress",
    start_date: "2024-01-15",
    end_date: "2024-11-30",
    budget: 4800000,
    manager: "D. Patel",
    progress: 62,
    description: "Modernizing the downtown civic center with sustainable materials and smart systems.",
    image:
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "demo-2",
    name: "Riverside Corporate Campus",
    location: "Austin, TX",
    status: "pending",
    start_date: "2024-03-05",
    end_date: "2025-02-18",
    budget: 6200000,
    manager: "S. Moreno",
    progress: 18,
    description: "Four-building corporate headquarters with collaborative outdoor spaces.",
    image:
      "https://images.unsplash.com/photo-1531835551805-16d864c8d949?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "demo-3",
    name: "Harborview Residences",
    location: "Seattle, WA",
    status: "completed",
    start_date: "2023-02-01",
    end_date: "2024-04-12",
    budget: 3550000,
    manager: "A. Chen",
    progress: 100,
    description: "Seventy-unit waterfront community with mixed-use retail and green rooftops.",
    image:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "demo-4",
    name: "Innovation Science Park",
    location: "Raleigh, NC",
    status: "in-progress",
    start_date: "2023-09-20",
    end_date: "2024-12-05",
    budget: 7800000,
    manager: "M. Thompson",
    progress: 74,
    description: "Cutting-edge research park with integrated laboratories and collaboration hubs.",
    image:
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
  },
];

export const sampleReports = [
  {
    id: "report-1",
    project_id: "demo-1",
    project_name: "Downtown Civic Center",
    status: "in-progress",
    summary: "Steel structure installation is 85% complete with inspections scheduled next week.",
    report_date: "2024-07-08",
    submitted_by: "D. Patel",
    health: "on-track",
  },
  {
    id: "report-2",
    project_id: "demo-2",
    project_name: "Riverside Corporate Campus",
    status: "pending",
    summary: "Permitting finalized. Groundbreaking ceremony planned for early August.",
    report_date: "2024-07-05",
    submitted_by: "S. Moreno",
    health: "upcoming",
  },
  {
    id: "report-3",
    project_id: "demo-3",
    project_name: "Harborview Residences",
    status: "completed",
    summary: "Final walkthrough completed. Tenants begin move-in next week.",
    report_date: "2024-06-27",
    submitted_by: "A. Chen",
    health: "completed",
  },
  {
    id: "report-4",
    project_id: "demo-4",
    project_name: "Innovation Science Park",
    status: "in-progress",
    summary: "Lab fit-outs progressing. Electrical rework required on Building C.",
    report_date: "2024-07-03",
    submitted_by: "M. Thompson",
    health: "at-risk",
  },
];
